
-- SRS §13 RBAC matrix - 14 functional domains, seeded once. permissions/role_permissions
-- tables already existed with correct schema but were never populated or wired to any code.
insert into permissions (code, domain, description) values
  ('dashboard_exec', 'reservations', 'Dashboard exécutif'),
  ('reserve_standard', 'reservations', 'Réserver poste standard'),
  ('edit_own_reservation', 'reservations', 'Modifier sa réservation'),
  ('edit_others_reservation', 'reservations', 'Modifier réservation d''autrui'),
  ('approve_long_duration', 'gouvernance', 'Approuver longue durée'),
  ('authorize_cluster_management', 'gouvernance', 'Autoriser cluster management'),
  ('manage_workstations', 'referentiels', 'Gérer postes'),
  ('manage_clusters', 'referentiels', 'Gérer clusters'),
  ('manage_users', 'administration', 'Gérer utilisateurs'),
  ('manage_roles', 'administration', 'Gérer rôles & permissions'),
  ('reservation_settings', 'administration', 'Paramètres de réservation'),
  ('audit_logs', 'gouvernance', 'Journaux d''audit'),
  ('analytics', 'gouvernance', 'Analytics & tableaux de bord'),
  ('technical_administration', 'technique', 'Administration technique')
on conflict (code) do nothing;

-- (role_code, permission_code, can_read, can_create, can_update, can_delete, can_approve)
insert into role_permissions (role_id, permission_id, can_read, can_create, can_update, can_delete, can_approve)
select r.id, p.id, v.cr, v.cc, v.cu, v.cd, v.ca
from (values
  -- dashboard_exec
  ('SUPER_ADMIN','dashboard_exec',true,false,false,false,false),
  ('ADMIN','dashboard_exec',true,false,false,false,false),
  ('BUILDING_MANAGER','dashboard_exec',true,false,false,false,false),
  ('GCI_MANAGER','dashboard_exec',true,false,false,false,false),
  ('RECEPTIONIST','dashboard_exec',false,false,false,false,false),
  ('EXECUTIVE_ASSISTANT','dashboard_exec',true,false,false,false,false),
  ('DIRECTOR','dashboard_exec',true,false,false,false,false),
  ('EMPLOYEE','dashboard_exec',false,false,false,false,false),
  ('IT_ADMIN','dashboard_exec',true,false,false,false,false),
  ('SECURITY','dashboard_exec',false,false,false,false,false),
  -- reserve_standard
  ('SUPER_ADMIN','reserve_standard',false,true,false,false,false),
  ('ADMIN','reserve_standard',false,true,false,false,false),
  ('BUILDING_MANAGER','reserve_standard',false,true,false,false,false),
  ('GCI_MANAGER','reserve_standard',false,true,false,false,false),
  ('RECEPTIONIST','reserve_standard',false,true,false,false,false),
  ('EXECUTIVE_ASSISTANT','reserve_standard',false,true,false,false,false),
  ('DIRECTOR','reserve_standard',false,true,false,false,false),
  ('EMPLOYEE','reserve_standard',false,true,false,false,false),
  ('IT_ADMIN','reserve_standard',false,true,false,false,false),
  ('SECURITY','reserve_standard',false,false,false,false,false),
  -- edit_own_reservation
  ('SUPER_ADMIN','edit_own_reservation',false,false,true,false,false),
  ('ADMIN','edit_own_reservation',false,false,true,false,false),
  ('BUILDING_MANAGER','edit_own_reservation',false,false,true,false,false),
  ('GCI_MANAGER','edit_own_reservation',false,false,true,false,false),
  ('RECEPTIONIST','edit_own_reservation',false,false,true,false,false),
  ('EXECUTIVE_ASSISTANT','edit_own_reservation',false,false,true,false,false),
  ('DIRECTOR','edit_own_reservation',false,false,true,false,false),
  ('EMPLOYEE','edit_own_reservation',false,false,true,false,false),
  ('IT_ADMIN','edit_own_reservation',false,false,true,false,false),
  ('SECURITY','edit_own_reservation',false,false,false,false,false),
  -- edit_others_reservation
  ('SUPER_ADMIN','edit_others_reservation',false,false,true,false,false),
  ('ADMIN','edit_others_reservation',false,false,true,false,false),
  ('BUILDING_MANAGER','edit_others_reservation',false,false,true,false,false),
  ('GCI_MANAGER','edit_others_reservation',false,false,true,false,false),
  ('RECEPTIONIST','edit_others_reservation',false,false,true,false,false),
  ('EXECUTIVE_ASSISTANT','edit_others_reservation',false,false,false,false,false),
  ('DIRECTOR','edit_others_reservation',false,false,false,false,false),
  ('EMPLOYEE','edit_others_reservation',false,false,false,false,false),
  ('IT_ADMIN','edit_others_reservation',false,false,false,false,false),
  ('SECURITY','edit_others_reservation',false,false,false,false,false),
  -- approve_long_duration
  ('SUPER_ADMIN','approve_long_duration',false,false,false,false,true),
  ('ADMIN','approve_long_duration',false,false,false,false,true),
  ('BUILDING_MANAGER','approve_long_duration',false,false,false,false,false),
  ('GCI_MANAGER','approve_long_duration',false,false,false,false,false),
  ('RECEPTIONIST','approve_long_duration',false,false,false,false,false),
  ('EXECUTIVE_ASSISTANT','approve_long_duration',false,false,false,false,true),
  ('DIRECTOR','approve_long_duration',false,false,false,false,true),
  ('EMPLOYEE','approve_long_duration',false,false,false,false,false),
  ('IT_ADMIN','approve_long_duration',false,false,false,false,false),
  ('SECURITY','approve_long_duration',false,false,false,false,false),
  -- authorize_cluster_management
  ('SUPER_ADMIN','authorize_cluster_management',false,false,false,false,true),
  ('ADMIN','authorize_cluster_management',false,false,false,false,true),
  ('BUILDING_MANAGER','authorize_cluster_management',false,false,false,false,true),
  ('GCI_MANAGER','authorize_cluster_management',false,false,false,false,true),
  ('RECEPTIONIST','authorize_cluster_management',false,false,false,false,false),
  ('EXECUTIVE_ASSISTANT','authorize_cluster_management',false,false,false,false,false),
  ('DIRECTOR','authorize_cluster_management',false,false,false,false,false),
  ('EMPLOYEE','authorize_cluster_management',false,false,false,false,false),
  ('IT_ADMIN','authorize_cluster_management',false,false,false,false,false),
  ('SECURITY','authorize_cluster_management',false,false,false,false,false),
  -- manage_workstations
  ('SUPER_ADMIN','manage_workstations',true,true,true,true,false),
  ('ADMIN','manage_workstations',true,true,true,true,false),
  ('BUILDING_MANAGER','manage_workstations',true,false,true,false,false),
  ('GCI_MANAGER','manage_workstations',true,false,true,false,false),
  ('RECEPTIONIST','manage_workstations',true,false,false,false,false),
  ('EXECUTIVE_ASSISTANT','manage_workstations',true,false,false,false,false),
  ('DIRECTOR','manage_workstations',true,false,false,false,false),
  ('EMPLOYEE','manage_workstations',true,false,false,false,false),
  ('IT_ADMIN','manage_workstations',true,false,false,false,false),
  ('SECURITY','manage_workstations',true,false,false,false,false),
  -- manage_clusters
  ('SUPER_ADMIN','manage_clusters',true,true,true,true,false),
  ('ADMIN','manage_clusters',true,true,true,true,false),
  ('BUILDING_MANAGER','manage_clusters',true,false,true,false,false),
  ('GCI_MANAGER','manage_clusters',true,false,true,false,false),
  ('RECEPTIONIST','manage_clusters',true,false,false,false,false),
  ('EXECUTIVE_ASSISTANT','manage_clusters',true,false,false,false,false),
  ('DIRECTOR','manage_clusters',true,false,false,false,false),
  ('EMPLOYEE','manage_clusters',true,false,false,false,false),
  ('IT_ADMIN','manage_clusters',true,false,false,false,false),
  ('SECURITY','manage_clusters',true,false,false,false,false),
  -- manage_users
  ('SUPER_ADMIN','manage_users',true,true,true,true,false),
  ('ADMIN','manage_users',true,true,true,true,false),
  ('BUILDING_MANAGER','manage_users',true,false,false,false,false),
  ('GCI_MANAGER','manage_users',true,false,false,false,false),
  ('RECEPTIONIST','manage_users',false,false,false,false,false),
  ('EXECUTIVE_ASSISTANT','manage_users',false,false,false,false,false),
  ('DIRECTOR','manage_users',false,false,false,false,false),
  ('EMPLOYEE','manage_users',false,false,false,false,false),
  ('IT_ADMIN','manage_users',true,false,false,false,false),
  ('SECURITY','manage_users',false,false,false,false,false),
  -- manage_roles
  ('SUPER_ADMIN','manage_roles',true,true,true,true,false),
  ('ADMIN','manage_roles',true,false,false,false,false),
  ('BUILDING_MANAGER','manage_roles',false,false,false,false,false),
  ('GCI_MANAGER','manage_roles',false,false,false,false,false),
  ('RECEPTIONIST','manage_roles',false,false,false,false,false),
  ('EXECUTIVE_ASSISTANT','manage_roles',false,false,false,false,false),
  ('DIRECTOR','manage_roles',false,false,false,false,false),
  ('EMPLOYEE','manage_roles',false,false,false,false,false),
  ('IT_ADMIN','manage_roles',true,false,false,false,false),
  ('SECURITY','manage_roles',false,false,false,false,false),
  -- reservation_settings
  ('SUPER_ADMIN','reservation_settings',true,true,true,true,false),
  ('ADMIN','reservation_settings',true,true,true,true,false),
  ('BUILDING_MANAGER','reservation_settings',true,false,false,false,false),
  ('GCI_MANAGER','reservation_settings',true,false,false,false,false),
  ('RECEPTIONIST','reservation_settings',false,false,false,false,false),
  ('EXECUTIVE_ASSISTANT','reservation_settings',false,false,false,false,false),
  ('DIRECTOR','reservation_settings',false,false,false,false,false),
  ('EMPLOYEE','reservation_settings',false,false,false,false,false),
  ('IT_ADMIN','reservation_settings',true,false,false,false,false),
  ('SECURITY','reservation_settings',false,false,false,false,false),
  -- audit_logs
  ('SUPER_ADMIN','audit_logs',true,false,false,false,false),
  ('ADMIN','audit_logs',true,false,false,false,false),
  ('BUILDING_MANAGER','audit_logs',true,false,false,false,false),
  ('GCI_MANAGER','audit_logs',true,false,false,false,false),
  ('RECEPTIONIST','audit_logs',false,false,false,false,false),
  ('EXECUTIVE_ASSISTANT','audit_logs',false,false,false,false,false),
  ('DIRECTOR','audit_logs',true,false,false,false,false),
  ('EMPLOYEE','audit_logs',false,false,false,false,false),
  ('IT_ADMIN','audit_logs',true,false,false,false,false),
  ('SECURITY','audit_logs',true,false,false,false,false),
  -- analytics
  ('SUPER_ADMIN','analytics',true,false,false,false,false),
  ('ADMIN','analytics',true,false,false,false,false),
  ('BUILDING_MANAGER','analytics',true,false,false,false,false),
  ('GCI_MANAGER','analytics',true,false,false,false,false),
  ('RECEPTIONIST','analytics',false,false,false,false,false),
  ('EXECUTIVE_ASSISTANT','analytics',true,false,false,false,false),
  ('DIRECTOR','analytics',true,false,false,false,false),
  ('EMPLOYEE','analytics',false,false,false,false,false),
  ('IT_ADMIN','analytics',true,false,false,false,false),
  ('SECURITY','analytics',true,false,false,false,false),
  -- technical_administration
  ('SUPER_ADMIN','technical_administration',true,false,false,false,false),
  ('ADMIN','technical_administration',false,false,false,false,false),
  ('BUILDING_MANAGER','technical_administration',false,false,false,false,false),
  ('GCI_MANAGER','technical_administration',false,false,false,false,false),
  ('RECEPTIONIST','technical_administration',false,false,false,false,false),
  ('EXECUTIVE_ASSISTANT','technical_administration',false,false,false,false,false),
  ('DIRECTOR','technical_administration',false,false,false,false,false),
  ('EMPLOYEE','technical_administration',false,false,false,false,false),
  ('IT_ADMIN','technical_administration',true,true,true,true,false),
  ('SECURITY','technical_administration',false,false,false,false,false)
) as v(role_code, permission_code, cr, cc, cu, cd, ca)
join roles r on r.code = v.role_code
join permissions p on p.code = v.permission_code
on conflict (role_id, permission_id) do update set
  can_read = excluded.can_read,
  can_create = excluded.can_create,
  can_update = excluded.can_update,
  can_delete = excluded.can_delete,
  can_approve = excluded.can_approve;
